AWSTemplateFormatVersion: 2010-09-09

Parameters:
  KeyName:
    Description: 'Optional key pair of the ec2-user to establish a SSH connection to the EC2 instance.'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: '1'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:

  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: 10.0.0.0/16

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24

  PublicRouteTables:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTables
      GatewayId: !Ref InternetGateway
    DependsOn:
      - EC2VPCG4UI66

  TomcatSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow access from HTTP and SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  EC2SRTA2KT4E:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTables
      SubnetId: !Ref PublicSubnet

  EC2VPCG4UI66:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
    
  TomcatServer:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.eu-west-3.amazonaws.com/cf-templates-1ldvye973texh-eu-west-3/2019125kAE-tomcat-v.2.505yv0c5q8k6q
      TimeoutInMinutes: '60'
      Parameters:
        KeyName:
          Ref: KeyName
        TomcatSecurityGroup:
          Ref: TomcatSecurityGroup
        PublicSubnet:
          Ref: PublicSubnet
    DependsOn:
      - PublicRoute

Outputs:
  StackRef:
     Value: !Ref TomcatServer
  PublicIP:
     Value: !GetAtt TomcatServer.Outputs.PublicIP
  OutputfromNestedStackPublicDNS:
     Value: !GetAtt TomcatServer.Outputs.PublicDNS
  Output1fromNestedStack:
     Value: !GetAtt TomcatServer.Outputs.InstanceId
     
