AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: "PROD"
  KeyName:
    Description: 'Optional key pair of the ec2-user to establish a SSH connection to the EC2 instance.'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: '1'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:

  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: 10.0.0.0/16

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}

  GatewayAttachmentInternet:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

#==================================================== Public Subnet =========	  
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24

#====== Public RouteTables =========	  
  PublicRouteTables:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ " ", [ !Ref Environment, "PublicRouteTables" ] ]

#======= Routes for Public Subnet RouteTables with IGW 
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTables
      GatewayId: !Ref InternetGateway
    DependsOn:
      - GatewayAttachmentInternet

#====== Associate Public Route for Public Subnets
  RouteAssociationPublicSubnet:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTables
      SubnetId: !Ref PublicSubnet

#==================================================== Privat Subnet =========	  
  PrivatSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24

#====== Privat RouteTables =========	  
  PrivatRouteTables:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ " ", [ !Ref Environment, "PrivatRouteTables" ] ]

#======= Routes for Privat Subnet RouteTables with IGW 
  PrivatRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrivatRouteTables
      GatewayId: !Ref InternetGateway
    DependsOn:
      - GatewayAttachmentInternet

#====== Associate Privat Route for Public Subnets
  RouteAssociationPrivatSubnet:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PrivatRouteTables
      SubnetId: !Ref PrivatSubnet

#====== Nested STECK with PublicServers (FrontEnd)

  PublicServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-3.amazonaws.com/cf-templates-1ldvye973texh-eu-west-3/2019129hlN-tomcat-v.2.9ms7h2wmbvd8
      TimeoutInMinutes: '60'
      Parameters:
        KeyName:
          Ref: KeyName
        VPC:
          Ref: VPC
        PublicSubnet:
          Ref: PublicSubnet
    DependsOn:
      - PublicRoute

Outputs:
  StackRef:
     Value: !Ref PublicServer
  TomcatPublicIP:
     Value: !GetAtt PublicServer.Outputs.PublicIP
  TomcatPublicDNS:
     Value: !GetAtt PublicServer.Outputs.PublicDNS
  TomcatInstanceId:
     Value: !GetAtt PublicServer.Outputs.InstanceId
  ZabbixPublicIP:
     Value: !GetAtt PublicServer.Outputs.ZabbixPublicIP
  ZabbixPublicDNS:
     Value: !GetAtt PublicServer.Outputs.ZabbixPublicDNS
  ZabbixInstanceId:
     Value: !GetAtt PublicServer.Outputs.ZabbixInstanceId
     
