# ==================== agent
# [root@puppetA puppet]# cat /etc/puppetlabs/puppet/puppet.conf
# # This file can be used to override the default puppet settings.
# # See the following links for more details on what settings are available:
# # - https://puppet.com/docs/puppet/latest/config_important_settings.html
# # - https://puppet.com/docs/puppet/latest/config_about_settings.html
# # - https://puppet.com/docs/puppet/latest/config_file_main.html
# # - https://puppet.com/docs/puppet/latest/configuration.html
# [main]
#  certname = puppet-cl.local
#  server = puppet-srv.local
#  environment = production
#  runinterval = 1h
# [agent]
#  environment = production
# ======================== master
# vi ../puppet/puppet.conf
# # This file can be used to override the default puppet settings.
# # See the following links for more details on what settings are available:
# # - https://puppet.com/docs/puppet/latest/config_important_settings.html
# # - https://puppet.com/docs/puppet/latest/config_about_settings.html
# # - https://puppet.com/docs/puppet/latest/config_file_main.html
# # - https://puppet.com/docs/puppet/latest/configuration.html
# [master]
# dns_alt_names = puppet-srv.local, puppet
# vardir = /opt/puppetlabs/server/data/puppetserver
# logdir = /var/log/puppetlabs/puppetserver
# rundir = /var/run/puppetlabs/puppetserver
# pidfile = /var/run/puppetlabs/puppetserver/puppetserver.pid
# codedir = /etc/puppetlabs/code
# [main]
# certname = puppet-srv.local
# server = puppet-srv.local
# environment = production
# runinterval = 1h

# vi environments/production/manifests/site.pp
# node 'puppet-cl.local' {
#   include zabbixserver
# }

# vi environments/production/modules/zabbixserver/manifests/params.pp
# class zabbixserver::params
# {
#   $baseurl            = ""
#   $gpgkey             = ""
#   $zabbix_packages    = ["zabbix-server-mysql", "zabbix-agent", "zabbix-web-mysql", "zabbix-java-gateway", "httpd", "php" ]
#   $mysqlpassword_root = 'Zabbix_2015'
#   $zabbix_db_name     = 'zabbix'
#   $zabbix_db_user     = 'zabbix'
#   $zabbix_db_password = 'zabbix'
#   $timezone           = 'Europe/Kiev'
# }

# vi environments/production/modules/zabbixserver/manifests/init.pp
# class zabbixserver (
#   $mysqlpassword_root = $zabbixserver::params::mysqlpassword_root,
#   $zabbix_db_name     = $zabbixserver::params::zabbix_db_name,
#   $zabbix_db_user     = $zabbixserver::params::zabbix_db_user,
#   $zabbix_db_password = $zabbixserver::params::zabbix_db_password,
# ) inherits zabbixserver::params
# {
#   notify { "Zabbix db name = $zabbix_db_name" : }
#   notify { "Zabbix db user = $zabbix_db_user" : }
#   notify { "Zabbix db password = $zabbix_db_password" : }
#   notify { "Zabbix root password for mysql = $mysqlpassword_root" : }
#   notify { "Zabbix packages = $zabbixserver::params::zabbix_packages" : }
# }