---
# tasks file for icinga2-ansible-web2-ui
- set_fact:
    mysql_password: "{{ pwd_alias }}$"

- name: Install MySQL 5.7 and Icinga2 repos
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
    - https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm

- name: Install MySQL, httpd, epel and scl repos
  yum:
    name: "{{ item }}"
  loop:
    - epel-release
    - centos-release-scl
    - mysql-community-server
    - mysql-community-client
    - MySQL-python
    - httpd

- name: Start the MySQL and httpd service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - mysqld
    - httpd

- name: Change mysql root password and keep track in and store it in /root/.my.cnf
  shell: |
    password_match=`awk '/A temporary password is generated for/ { print $NF }' /var/log/mysqld.log`
    mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_password }}'; flush privileges; "
    echo "[client]
    user=root
    password={{ mysql_password }}" > /root/.my.cnf
  args:
    creates: /root/.my.cnf
  register: change_temp_pass

- debug:
    msg: "MySQL root password {{ mysql_password }}"

- name: Install PHP
  yum:
    name: "{{ item }}"
  loop:
    - rh-php71-php-mysqlnd
    - rh-php71-php-cli
    - php-Icinga
    - rh-php71-php-common
    - rh-php71-php-fpm
    - rh-php71-php-pgsql
    - rh-php71-php-ldap
    - rh-php71-php-intl
    - rh-php71-php-xml
    - rh-php71-php-gd
    - rh-php71-php-pdo
    - rh-php71-php-mbstring

- name: Find out timezone
  slurp:
     src: /etc/localtime
  register: etc_localtime

- name: Timezone in php.ini
  lineinfile:
    path: /etc/opt/rh/rh-php71/php.ini
    regexp: '^;?date.timezone ='
    line: 'date.timezone = Europe/Kiev'

- name: Install icinga2
  yum:
    name: "{{ item }}"
  loop:
    - icinga2
    - icinga2-ido-mysql
    - icingaweb2
    - icingacli
    - nagios-plugins-all
    - icingaweb2-selinux
    - icinga2-selinux

- import_tasks: icinga2_web2_create_databases.yml

- name: Start the icinga2 and rh-php71-php-fpm service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - icinga2
    - rh-php71-php-fpm

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Get setup token.
  shell: 'icingacli setup token create | sed "s/.*token is: \(.*\)/\1/g"'
  register: setup_token

- name: Icinga Web2 Installation finished
  debug:
    msg: "The WebUI token is {{ setup_token.stdout }}, us it at http://IP//icingaweb2/setup to continue the installation"

#$ touch /var/www/html/index.html
#$ chmod 755 /var/www/html/index.html

# ===================================================    client install ==============
# yum install https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
# yum install icinga2
# yum install epel-release
# yum install nagios-plugins-all
# # RHEL sudo rpm -Uvh https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
# # RHEL subscription-manager repos --enable rhel-7-server-optional-rpms
# yum install icinga2-selinux
# icinga2 node wizard

# ======================   add host in Icinga2 serveer into 
# # https://www.techrepublic.com/article/how-to-add-remote-hosts-to-the-icinga2-monitoring-system/
# vi /etc/icinga2/conf.d/hosts.conf
# ------------------------
# object Host "icinga2c" {
#   import "generic-host"
#   address = "192.168.237.106"
#   check_command = "hostalive"
# }
# ------------------------
# systemctl restart icinga2
# ==========================  API install / config
# icinga2 feature list
# icinga2 feature enable api
# icinga2 api setup
# systemctl restart icinga2
# ==========================  director install / config
# username = "director"
# password = "ifVaysRZTnV1fWj7qqjT$"

# CREATE DATABASE director CHARACTER SET 'utf8'; GRANT ALL ON director.* TO director@localhost IDENTIFIED BY 'ifVaysRZTnV1fWj7qqjT$';
# yum install -y git

# mkdir -p /usr/share/icingaweb2/modules
# cd /usr/share/icingaweb2/modules
# sudo git clone https://github.com/Icinga/icingaweb2-module-director.git director

# vi /etc/icingaweb2/resources.ini
# [Director DB]
# type = "db"
# db = "mysql"
# host = "localhost"
# dbname = "director"
# username = "director"
# password = "ifVaysRZTnV1fWj7qqjT$"
# charset = "utf8"

# vi /etc/icinga2/conf.d/api-users.conf
# object ApiUser "director" {
#   password = "ifVaysRZTnV1fWj7qqjT$"
#   permissions = [ "*" ]
# }
	
# sudo service icinga2 restart

# https://blog.it-kb.ru/2017/01/25/deploy-and-configure-icinga-2-on-debian-8-6-part-6-icinga-director-1-2-0-deployment-and-configuration-of-zones-commands-services-host-templates/
# https://www.howtoforge.com/tutorial/add-a-new-host-and-service-to-be-monitored-by-icinga2/
# https://www.howtoforge.com/how-to-add-hosts-to-icinga2-using-the-icinga-director/


# icinga2 object list --type CheckCommand --name nrpe
# cat /usr/share/icinga2/include/command-plugins.conf
# /usr/lib64/nagios/plugins/
# rpm -ql icinga2
# rpm -qa | grep nagios

# /etc/icinga2/conf.d/
# /etc/icinga2/conf.d/hosts.conf - local host config
# /etc/icinga2/conf.d/template.conf  - local template

# template Host "P1" {
#   import "generic-host"
#   max_check_attempts = 3
#   check_interval = 1m
#   retry_interval = 30s

#   check_command = "hostalive"
# }

# template Host "P2" {
#   import "generic-host"
#   max_check_attempts = 4
#   check_interval = 5m
#   retry_interval = 30s

#   check_command = "hostalive"
# }

# template Host "P3" {
#   import "generic-host"
#   max_check_attempts = 5
#   check_interval = 15m
#   retry_interval = 30s

#   check_command = "hostalive"
# }

# template Host "P1" {
#   import "generic-host"
#   max_check_attempts = 3
#   check_interval = 1m
#   retry_interval = 30s

#   check_command = "hostalive"
# }

# template Host "P2" {
#   import "generic-host"
#   max_check_attempts = 4
#   check_interval = 5m
#   retry_interval = 30s

#   check_command = "hostalive"
# }

# template Host "P3" {
#   import "generic-host"
#   max_check_attempts = 5
#   check_interval = 15m
#   retry_interval = 30s

#   check_command = "hostalive"
# }

# /etc/icinga2/conf.d/hosts.conf
# object Host "myhost1"  {
#   import "P2"
#   address = "127.0.0.1"
#   vars.os = "Linux"
#   vars.http_vhosts["http"] = {
#     http_uri = "/"
#   }
#   vars.disks["disk"] = {
#   }
#   vars.disks["disk /"] = {
#     disk_partitions = "/"
#   }
#   vars.notification["mail"] = {
#     groups = [ "icingaadmins" ]
#   }
# }